language: node_js
node_js:
 - "13"
 - "14"
cache: yarn
jobs:
  include:
   - stage: test
     script:
     - yarn
     - yarn test
stages:
 - name: test
   if: type = push
after_success:
 - wget https://raw.githubusercontent.com/minenode/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh success $WEBHOOK_URL
after_failure:
 - wget https://raw.githubusercontent.com/minenode/travis-ci-discord-webhook/master/send.sh
 - chmod +x send.sh
 - ./send.sh failure $WEBHOOK_URL
