/* eslint-disable license-header/header */

import { double, float, int } from "../data/NBT";

export const old = {
  "minecraft:dimension_type": {
    type: "minecraft:dimension_type",
    value: [
      {
        element: {
          shrunk: false,
          ambient_light: float(0.0),
          bed_works: true,
          coordinate_scale: double(1.0),
          effects: "minecraft:overworld",
          has_ceiling: false,
          has_raids: true,
          has_skylight: true,
          height: int(320),
          infiniburn: "#minecraft:infiniburn_overworld",
          logical_height: int(320),
          min_y: int(-64),
          natural: true,
          piglin_safe: false,
          respawn_anchor_works: false,
          ultrawarm: false,
        },
        id: int(0),
        name: "minecraft:overworld",
      },
    ],
  },
  "minecraft:worldgen/biome": {
    type: "minecraft:worldgen/biome",
    value: [
      {
        element: {
          category: "plains",
          downfall: float(0.4),
          effects: {
            sky_color: int(7907327),
            water_fog_color: int(329011),
            fog_color: int(12638463),
            water_color: int(4159204),
            mood_sound: {
              tick_delay: int(6000),
              offset: double(2.0),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
            },
          },
          depth: float(0.125),
          precipitation: "rain",
          temperature: float(0.8),
          scale: float(0.05),
        },
        id: int(1),
        name: "minecraft:plains",
      },
    ],
  },
};

export default {
  "minecraft:dimension_type": {
    type: "minecraft:dimension_type",
    value: [
      {
        name: "minecraft:overworld",
        id: int(0),
        element: {
          infiniburn: "#minecraft:infiniburn_overworld",
          effects: "minecraft:overworld",
          ultrawarm: false,
          logical_height: int(384),
          height: int(384),
          natural: true,
          min_y: int(-64),
          bed_works: true,
          coordinate_scale: double(1),
          piglin_safe: false,
          has_skylight: true,
          has_ceiling: false,
          ambient_light: float(0),
          has_raids: true,
          respawn_anchor_works: false,
        },
      },
      {
        name: "minecraft:overworld_caves",
        id: int(1),
        element: {
          infiniburn: "#minecraft:infiniburn_overworld",
          effects: "minecraft:overworld",
          ultrawarm: false,
          logical_height: int(384),
          height: int(384),
          natural: true,
          min_y: int(-64),
          bed_works: true,
          coordinate_scale: double(1),
          piglin_safe: false,
          has_skylight: true,
          has_ceiling: true,
          ambient_light: float(0),
          has_raids: true,
          respawn_anchor_works: false,
        },
      },
      {
        name: "minecraft:the_nether",
        id: int(2),
        element: {
          infiniburn: "#minecraft:infiniburn_nether",
          effects: "minecraft:the_nether",
          ultrawarm: true,
          logical_height: int(128),
          height: int(256),
          natural: false,
          min_y: int(0),
          bed_works: false,
          fixed_time: BigInt(18000),
          coordinate_scale: double(8),
          piglin_safe: true,
          has_ceiling: true,
          has_skylight: false,
          ambient_light: float(0.10000000149011612),
          has_raids: false,
          respawn_anchor_works: true,
        },
      },
      {
        name: "minecraft:the_end",
        id: int(3),
        element: {
          infiniburn: "#minecraft:infiniburn_end",
          effects: "minecraft:the_end",
          ultrawarm: false,
          logical_height: int(256),
          height: int(256),
          natural: false,
          min_y: int(0),
          bed_works: false,
          fixed_time: BigInt(6000),
          coordinate_scale: double(1),
          piglin_safe: false,
          has_ceiling: false,
          has_skylight: false,
          ambient_light: float(0),
          has_raids: true,
          respawn_anchor_works: false,
        },
      },
    ],
  },
  "minecraft:worldgen/biome": {
    type: "minecraft:worldgen/biome",
    value: [
      {
        name: "minecraft:the_void",
        id: int(0),
        element: {
          category: "none",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },

          precipitation: "none",
        },
      },
      {
        name: "minecraft:plains",
        id: int(1),
        element: {
          category: "plains",
          temperature: float(0.800000011920929),
          downfall: float(0.4000000059604645),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },

            sky_color: int(7907327),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:sunflower_plains",
        id: int(2),
        element: {
          category: "plains",
          temperature: float(0.800000011920929),
          downfall: float(0.4000000059604645),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7907327),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:snowy_plains",
        id: int(3),
        element: {
          category: "icy",
          temperature: float(0),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8364543),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:ice_spikes",
        id: int(4),
        element: {
          category: "icy",
          temperature: float(0),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8364543),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:desert",
        id: int(5),
        element: {
          category: "desert",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:swamp",
        id: int(6),
        element: {
          category: "swamp",
          temperature: float(0.800000011920929),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(2302743),
            water_color: int(6388580),
            foliage_color: int(6975545),
            grass_color_modifier: "swamp",
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7907327),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:forest",
        id: int(7),
        element: {
          category: "forest",
          temperature: float(0.699999988079071),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7972607),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:flower_forest",
        id: int(8),
        element: {
          category: "forest",
          temperature: float(0.699999988079071),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7972607),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:birch_forest",
        id: int(9),
        element: {
          category: "forest",
          temperature: float(0.6000000238418579),
          downfall: float(0.6000000238418579),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8037887),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:dark_forest",
        id: int(10),
        element: {
          category: "forest",
          temperature: float(0.699999988079071),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            grass_color_modifier: "dark_forest",
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7972607),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:old_growth_birch_forest",
        id: int(11),
        element: {
          category: "forest",
          temperature: float(0.6000000238418579),
          downfall: float(0.6000000238418579),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8037887),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:old_growth_pine_taiga",
        id: int(12),
        element: {
          category: "taiga",
          temperature: float(0.30000001192092896),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8168447),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:old_growth_spruce_taiga",
        id: int(13),
        element: {
          category: "taiga",
          temperature: float(0.25),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233983),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:taiga",
        id: int(14),
        element: {
          category: "taiga",
          temperature: float(0.25),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233983),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:snowy_taiga",
        id: int(15),
        element: {
          category: "taiga",
          temperature: float(-0.5),
          downfall: float(0.4000000059604645),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4020182),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8625919),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:savanna",
        id: int(16),
        element: {
          category: "savanna",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:savanna_plateau",
        id: int(17),
        element: {
          category: "savanna",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:windswept_hills",
        id: int(18),
        element: {
          category: "extreme_hills",
          temperature: float(0.20000000298023224),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233727),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:windswept_gravelly_hills",
        id: int(19),
        element: {
          category: "extreme_hills",
          temperature: float(0.20000000298023224),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233727),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:windswept_forest",
        id: int(20),
        element: {
          category: "extreme_hills",
          temperature: float(0.20000000298023224),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233727),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:windswept_savanna",
        id: int(21),
        element: {
          category: "savanna",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:jungle",
        id: int(22),
        element: {
          category: "jungle",
          temperature: float(0.949999988079071),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7842047),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:sparse_jungle",
        id: int(23),
        element: {
          category: "jungle",
          temperature: float(0.949999988079071),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7842047),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:bamboo_jungle",
        id: int(24),
        element: {
          category: "jungle",
          temperature: float(0.949999988079071),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7842047),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:badlands",
        id: int(25),
        element: {
          category: "mesa",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            grass_color: int(9470285),
            foliage_color: int(10387789),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:eroded_badlands",
        id: int(26),
        element: {
          category: "mesa",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            grass_color: int(9470285),
            foliage_color: int(10387789),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:wooded_badlands",
        id: int(27),
        element: {
          category: "mesa",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            grass_color: int(9470285),
            foliage_color: int(10387789),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:meadow",
        id: int(28),
        element: {
          category: "mountain",
          temperature: float(0.5),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(937679),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.meadow",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:grove",
        id: int(29),
        element: {
          category: "forest",
          temperature: float(-0.20000000298023224),
          downfall: float(0.800000011920929),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.grove",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8495359),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:snowy_slopes",
        id: int(30),
        element: {
          category: "mountain",
          temperature: float(-0.30000001192092896),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.snowy_slopes",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8560639),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:frozen_peaks",
        id: int(31),
        element: {
          category: "mountain",
          temperature: float(-0.699999988079071),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.frozen_peaks",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8756735),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:jagged_peaks",
        id: int(32),
        element: {
          category: "mountain",
          temperature: float(-0.699999988079071),
          downfall: float(0.8999999761581421),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.jagged_peaks",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8756735),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:stony_peaks",
        id: int(33),
        element: {
          category: "mountain",
          temperature: float(1),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.stony_peaks",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7776511),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:river",
        id: int(34),
        element: {
          category: "river",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:frozen_river",
        id: int(35),
        element: {
          category: "river",
          temperature: float(0),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(3750089),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8364543),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:beach",
        id: int(36),
        element: {
          category: "beach",
          temperature: float(0.800000011920929),
          downfall: float(0.4000000059604645),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7907327),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:snowy_beach",
        id: int(37),
        element: {
          category: "beach",
          temperature: float(0.05000000074505806),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4020182),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8364543),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:stony_shore",
        id: int(38),
        element: {
          category: "beach",
          temperature: float(0.20000000298023224),
          downfall: float(0.30000001192092896),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8233727),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:warm_ocean",
        id: int(39),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(270131),
            water_color: int(4445678),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:lukewarm_ocean",
        id: int(40),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(267827),
            water_color: int(4566514),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:deep_lukewarm_ocean",
        id: int(41),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(267827),
            water_color: int(4566514),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:ocean",
        id: int(42),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:deep_ocean",
        id: int(43),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:cold_ocean",
        id: int(44),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4020182),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:deep_cold_ocean",
        id: int(45),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4020182),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:frozen_ocean",
        id: int(46),
        element: {
          category: "ocean",
          temperature: float(0),
          downfall: float(0.5),
          temperature_modifier: "frozen",
          effects: {
            water_fog_color: int(329011),
            water_color: int(3750089),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8364543),
          },
          precipitation: "snow",
        },
      },
      {
        name: "minecraft:deep_frozen_ocean",
        id: int(47),
        element: {
          category: "ocean",
          temperature: float(0.5),
          downfall: float(0.5),
          temperature_modifier: "frozen",
          effects: {
            water_fog_color: int(329011),
            water_color: int(3750089),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:mushroom_fields",
        id: int(48),
        element: {
          category: "mushroom",
          temperature: float(0.8999999761581421),
          downfall: float(1),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7842047),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:dripstone_caves",
        id: int(49),
        element: {
          category: "underground",
          temperature: float(0.800000011920929),
          downfall: float(0.4000000059604645),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.dripstone_caves",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7907327),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:lush_caves",
        id: int(50),
        element: {
          category: "underground",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.overworld.lush_caves",
              replace_current_music: false,
              min_delay: int(12000),
            },
            fog_color: int(12638463),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(8103167),
          },
          precipitation: "rain",
        },
      },
      {
        name: "minecraft:nether_wastes",
        id: int(51),
        element: {
          category: "nether",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.nether.nether_wastes",
              replace_current_music: false,
              min_delay: int(12000),
            },
            additions_sound: {
              sound: "minecraft:ambient.nether_wastes.additions",
              tick_chance: double(0.0111),
            },
            fog_color: int(3344392),
            ambient_sound: "minecraft:ambient.nether_wastes.loop",
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.nether_wastes.mood",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:warped_forest",
        id: int(52),
        element: {
          category: "nether",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.nether.warped_forest",
              replace_current_music: false,
              min_delay: int(12000),
            },
            additions_sound: {
              sound: "minecraft:ambient.warped_forest.additions",
              tick_chance: double(0.0111),
            },
            fog_color: int(1705242),
            particle: {
              options: { type: "minecraft:warped_spore" },
              probability: float(0.014279999770224094),
            },
            ambient_sound: "minecraft:ambient.warped_forest.loop",
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.warped_forest.mood",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:crimson_forest",
        id: int(53),
        element: {
          category: "nether",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.nether.crimson_forest",
              replace_current_music: false,
              min_delay: int(12000),
            },
            additions_sound: {
              sound: "minecraft:ambient.crimson_forest.additions",
              tick_chance: double(0.0111),
            },
            fog_color: int(3343107),
            particle: {
              options: { type: "minecraft:crimson_spore" },
              probability: float(0.02500000037252903),
            },
            ambient_sound: "minecraft:ambient.crimson_forest.loop",
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.crimson_forest.mood",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:soul_sand_valley",
        id: int(54),
        element: {
          category: "nether",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.nether.soul_sand_valley",
              replace_current_music: false,
              min_delay: int(12000),
            },
            additions_sound: {
              sound: "minecraft:ambient.soul_sand_valley.additions",
              tick_chance: double(0.0111),
            },
            fog_color: int(1787717),
            particle: {
              options: { type: "minecraft:ash" },
              probability: float(0.0062500000931322575),
            },
            ambient_sound: "minecraft:ambient.soul_sand_valley.loop",
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.soul_sand_valley.mood",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:basalt_deltas",
        id: int(55),
        element: {
          category: "nether",
          temperature: float(2),
          downfall: float(0),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            music: {
              max_delay: int(24000),
              sound: "minecraft:music.nether.basalt_deltas",
              replace_current_music: false,
              min_delay: int(12000),
            },
            additions_sound: {
              sound: "minecraft:ambient.basalt_deltas.additions",
              tick_chance: double(0.0111),
            },
            fog_color: int(6840176),
            particle: {
              options: { type: "minecraft:white_ash" },
              probability: float(0.1180933341383934),
            },
            ambient_sound: "minecraft:ambient.basalt_deltas.loop",
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.basalt_deltas.mood",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(7254527),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:the_end",
        id: int(56),
        element: {
          category: "the_end",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(10518688),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(0),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:end_highlands",
        id: int(57),
        element: {
          category: "the_end",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(10518688),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(0),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:end_midlands",
        id: int(58),
        element: {
          category: "the_end",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(10518688),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(0),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:small_end_islands",
        id: int(59),
        element: {
          category: "the_end",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(10518688),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(0),
          },
          precipitation: "none",
        },
      },
      {
        name: "minecraft:end_barrens",
        id: int(60),
        element: {
          category: "the_end",
          temperature: float(0.5),
          downfall: float(0.5),
          effects: {
            water_fog_color: int(329011),
            water_color: int(4159204),
            fog_color: int(10518688),
            mood_sound: {
              offset: double(2),
              sound: "minecraft:ambient.cave",
              block_search_extent: int(8),
              tick_delay: int(6000),
            },
            sky_color: int(0),
          },
          precipitation: "none",
        },
      },
    ],
  },
};
