name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Test
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Build
        run: yarn build
      - name: Package
        run: yarn package
      - name: Publish (Windows x64)
        uses: actions/upload-artifact@v2
        with:
          name: minenode-windows-x64
          path: dist/minenode-windows.exe
      - name: Publish (Linux x64)
        uses: actions/upload-artifact@v2
        with:
          name: minenode-linux-x64
          path: dist/minenode-linux
      - name: Publish (MacOS x64)
        uses: actions/upload-artifact@v2
        with:
          name: minenode-macos-x64
          path: dist/minenode-macos
